"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-12

PLACEHOLDER: run this at 9:00 AM once the DB container is up:

    docker compose exec backend alembic revision --autogenerate -m "initial schema"

That will overwrite this file with the real autogenerated upgrade()/downgrade()
bodies based on the models in app/models/. This stub exists only so
0002_booking_exclude_constraint.py has a valid down_revision to chain from
and the migration history is readable from commit one.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass  # replaced by autogenerate at 9:00 AM


def downgrade() -> None:
    pass
