"""add composite index on assets status/category

Revision ID: 472840d76768
Revises: ddcaf8c837b8
Create Date: 2026-07-12 05:13:24.606642

"""
from alembic import op
import sqlalchemy as sa


revision = '472840d76768'
down_revision = 'ddcaf8c837b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_assets_status_category', 'assets', ['status', 'category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_status_category', table_name='assets')
    # ### end Alembic commands ###
